author:
  name: "Antonio Moreno"
  role: "Ingeniero en Ciencias de Datos"
  bio: "He analizado datos de comportamiento, rendimiento y eficiencia para optimizar decisiones estratégicas y modelos operativos.
  Me especializo en TI, business intelligence, operaciones y producto, integrando análisis y visión para convertir datos en acción. Agradezco a mis profesores Rav Ahuja (IBM) y Sebastian Raschka, 
  quienes reforzaron mi visión de la ciencia de datos como un puente entre el pensamiento analítico, la tecnología y el progreso humano."
  photo: "/assets/img/ia/fotoperfil.png"   # <-- aquí va el /ia/
  email: "anthoniomoreno1@gmail.com"
