title: "Blog de Antonio"
description: "Datos, tecnología y progreso."
url: "https://tny-me.github.io"  # tu usuario
baseurl: "/Blog"                  # nombre del repo con mayúscula si así está

# Tema oficial (no necesitas workflows ni Gemfile)
theme: jekyll-theme-cayman

# Navegación simple (opcional)
nav:
  - name: "Inicio"
    url: "/"
  - name: "Acerca"
    url: "/about/"
